#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import pickle, os
BASE='/Users/jairwang/Documents/Coding'
m1=pickle.load(open(os.path.join(BASE,'CTO','metrics.pkl'),'rb'))
m2=pickle.load(open(os.path.join(BASE,'CTO','metrics2.pkl'),'rb'))
g=dict(m1); g.update(m2)

PV=g['PV']; UV=g['UV']; SESSION=g['SESSION']
out=[]
A=out.append
A('# 微信客服 AI 对话日志数据分析报告')
A('')
A('> **分析周期**: 2026-04-18 00:00 ~ 2026-04-19 23:59（共 2 天）  ')
A(f'> **数据源**: `4ce9e6d8-e335-44af-9a70-cc327b308192.ndjson`（{PV:,} 条记录）  ')
A('> **协议依据**: `TrpcSmartKfConnectAiSvr`（微信客服/腾讯视频智能客服 AI 服务）  ')
A('> **报告生成日期**: 2026-04-20')
A('')
A('---')
A('')
A('## 一、核心概览')
A('')
A('| 指标 | 数值 | 说明 |')
A('|------|------|------|')
A(f'| 消息总量 (PV) | **{PV:,}** | 每条 ndjson = 一轮"用户提问 + AI 回复" |')
A(f'| 独立用户 (UV) | **{UV:,}** | 按 `openid` 去重 |')
A(f'| 会话总数 | **{SESSION:,}** | 按 `session_id` 去重 |')
A(f'| 人均消息 | {PV/UV:.2f} | 平均每用户消息数 |')
A(f'| 人均会话 | {SESSION/UV:.2f} | 平均每用户会话数 |')
A(f'| 平均会话轮数 | {g["cl_avg"]:.2f} | 中位 {g["cl_median"]}，最大 {g["cl_max"]} |')
A('')
A('### 业务场景分布')
A('')
A('| 业务场景 | `s_session_ai_scene` | 消息量 | 占比 | UV |')
A('|----------|------------------------|--------|------|-----|')
A(f'| 腾讯视频 VIP 智能客服（AI 纯自动应答） | 91000022 | {g["SCENE_TXSP"]:,} | {g["SCENE_TXSP"]/PV*100:.2f}% | {g["UV_TXSP"]:,} |')
A(f'| 微信客服（腾讯客服后台代答回调） | 91000069 | {g["SCENE_WXKF"]:,} | {g["SCENE_WXKF"]/PV*100:.2f}% | {g["UV_WXKF"]:,} |')
A('')
A(f'> **说明**：场景 `91000069` 全部 {g["SCENE_WXKF"]} 条的 `source_service` 均为 `kf_msg_callback_to_wx`，对应 proto 中 `TxKfSendMsgToUser`（腾讯客服发送消息到微信客服用户）——属**后台/人工介入通道**；场景 `91000022` 由 AI 纯自动应答（`source_service` 为 26/24/None）。')
A('')
A('---')
A('')
A('## 二、PV / UV 统计')
A('')
A('### 2.1 两日整体')
A('')
A('| 日期 | 消息量 (PV) | 环比 |')
A('|------|-------------|------|')
dates=sorted(g['date_cnt'].items())
base_val=dates[0][1]
for i,(d,c) in enumerate(dates):
    ring='—' if i==0 else f'{(c/base_val-1)*100:+.2f}%'
    A(f'| 2026-{d} | {c:,} | {ring} |')
A(f'| **合计** | **{PV:,}** | — |')
A('')
A(f'- 两日消息量基本持平，系统负载稳定。')
A(f'- 独立用户 UV **{UV:,}**，会话数 **{SESSION:,}**，人均约 {SESSION/UV:.2f} 次会话、{PV/UV:.2f} 条消息，典型"低频多问题"客服场景。')
A('')
A('---')
A('')
A('## 三、时间分布与热点时段')
A('')
A('### 3.1 24 小时消息量曲线')
A('')
A('| 小时 | 消息数 | 独立用户 | 占比 | 热力 |')
A('|------|--------|----------|------|------|')
for h in range(24):
    c=g['hour_cnt'].get(h,0); u=g['user_hour'].get(h,0); pct=c/PV*100
    bar='█'*max(1,int(pct*2))
    A(f'| {h:02d}:00 | {c:,} | {u:,} | {pct:.2f}% | `{bar}` |')
A('')
A('### 3.2 核心结论')
A('')
A('- **🔥 绝对峰值**：`13:00-13:59`，消息量 **2,162 条 / 占比 8.08%**，独立用户 698 人（午休咨询高峰）。')
A('- **🔥 持续高峰区间**：`10:00-15:00` 连续 6 小时，合计 **11,270 条**，占全天 **42.14%**。')
A('- **次高峰**：`20:00-22:00`（晚间追剧时段），合计 4,377 条，占 **16.37%**，与腾讯视频"晚间观影"业务特征吻合。')
A('- **低谷区间**：`05:00` 最低（80 条 / 0.30%），`03:00-06:00` 深夜合计仅 591 条（2.21%）。')
A('- **白班/夜班比**：08:00-20:00 占 **77.12%**；20:00-次日 08:00 占 22.88%。')
A('')
A('### 3.3 运营建议')
A('')
A('| 时段 | 建议 |')
A('|------|------|')
A('| 10:00-15:00（峰值）| AI 应答能力预留 ≥ 峰值 QPS 1.2 倍冗余；人工客服排班 +30%~50% |')
A('| 20:00-22:00（次峰）| 预热"追剧/播放问题"知识库；加强自动续费答复质量 |')
A('| 00:00-06:00（低谷）| 启用小模型降本分流；人工仅保留应急值班 |')
A('')
with open(os.path.join(BASE,'CTO','part1.md'),'w',encoding='utf-8') as f:
    f.write('\n'.join(out))
print('part1 md done, lines:', len(out))
